from enum import IntEnum


class SocketCodes(IntEnum):
    # TODO: Finish this Enum with other Codes.

    MESSAGE = 1000
    NOTIFICATION = 10

    TYPING_START = 304
    TYPING_END = 306


class MessageTypes(IntEnum):
    TEXT = 0
    STRIKE_MESSAGE = 1
    VOICE_MESSAGE = 2
    STICKER_MESSAGE = 3
    VOICE_CHAT_NOT_ANSWERED = 52
    VOICE_CHAT_NOT_CANCELLED = 53
    VOICE_CHAT_NOT_DECLINED = 54
    VIDEO_CHAT_NOT_ANSWERED = 55
    VIDEO_CHAT_NOT_CANCELLED = 56
    VIDEO_CHAT_NOT_DECLINED = 57
    AVATAR_CHAT_NOT_ANSWERED = 58
    AVATAR_CHAT_NOT_CANCELLED = 59
    AVATAR_CHAT_NOT_DECLINED = 60
    DELETE_MESSAGE = 100
    GROUP_MEMBER_JOIN = 101
    GROUP_MEMBER_LEAVE = 102
    CHAT_INVITE = 103
    CHAT_BACKGROUND_CHANGED = 104
    CHAT_TITLE_CHANGED = 105
    CHAT_ICON_CHANGED = 106
    VOICE_CHAT_START = 107
    VIDEO_CHAT_START = 108
    AVATAR_CHAT_START = 109
    VOICE_CHAT_END = 110
    VIDEO_CHAT_END = 111
    AVATAR_CHAT_END = 112
    CHAT_CONTENT_CHANGED = 113
    SCREEN_ROOM_START = 114
    SCREEN_ROOM_END = 115
    CHAT_HOST_TRANSFERED = 116
    TEXT_MESSAGE_FORCE_REMOVED = 117
    CHAT_REMOVED_MESSAGE = 118
    TEXT_MESSAGE_REMOVED_BY_ADMIN = 119
    CHAT_TIP = 120
    CHAT_PIN_ANNOUNCEMENT = 121
    VOICE_CHAT_PERMISSION_OPEN_TO_EVERYONE = 122
    VOICE_CHAT_PERMISSION_INVITED_AND_REQUESTED = 123
    VOICE_CHAT_PERMISSION_INVITE_ONLY = 124
    CHAT_VIEW_ONLY_ENABLED = 125
    CHAT_VIEW_ONLY_DISABLED = 126
    CHAT_UNPIN_ANNOUNCEMENT = 127
    CHAT_TIPPING_ENABLED = 128
    CHAT_TIPPING_DISABLED = 129
    TIMESTAMP_MESSAGE = 65281
    WELCOME_MESSAGE = 65282
    INVITE_MESSAGE = 65283
